### ISSUE TITLE
No roms

### ISSUE THREAD

**Issue by HttpAnimation** [Vysp3r/RetroPlus#1]
No game get loaded when opening on fedora 39 kde from flathub

![image](https://github.com/Vysp3r/RetroPlus/assets/97435656/77835f3a-2f1f-4574-bdb0-659384b0d33a)

**Comment by Vysp3r** [comment]
Have you actually tried to search for a game at least? It's normal that nothing loads at first, it's just like a search engine. When you go on google.com do you see results even before you search for a game? If you think adding something at under the search bar like 'Feels empty in here. Why not search for a game?' I definitely could.

**Comment by Vysp3r** [comment]
@HttpAnimation Have you found a solution to your question or do you still need help?

**Comment by Vysp3r** [comment]
Since there's no response from you, I will close the ticket to keep my issue list clean. I'll re-open it again if the issue becomes active again.
