### ISSUE TITLE
Display source

### ISSUE THREAD

**Issue by chanksworld** [Vysp3r/RetroPlus#10]
An additional tab with the rom source would be nice, downloading ninja gaiden black right now at ~164kpbs (!) and don't know from where. . also while typing this the download stopped at 11mb and disappeared from the DL list, not sure if a "continue download" option would be easy to implement but just mentioning it.  great app overall

**Comment by Vysp3r** [comment]
You can see the source of where you're searching for roms in the advanced filter menu. If you're asking to see what source you're downloading them from in the download popup that could be a nice thing to add.

As for your downloading stopping at 11mb they're was probably an error during the download and it got cancelled. You can see a toast notification when that happens, but I guess if you're not looking at the application you can't really see that something  wrong happened. Might need to rethink that.

**Comment by Vysp3r** [comment]
Closing since I am ending support support for RetroPlus.
Sorry for the inconvenience.
