### ISSUE TITLE
App Icon that fits the GNOME Human Interface Guidelines

### ISSUE THREAD

**Issue by sungsphinx** [Vysp3r/RetroPlus#14]
Hi, I noticed this app's icon doesn't fit in nicely with the [GNOME HIG](https://developer.gnome.org/hig/guidelines/app-icons.html), so I have put together this:

![image](https://github.com/Vysp3r/RetroPlus/assets/80914457/6cb4817c-cc4c-4fdd-9119-a975e15603c8)

I'm not the best at making app icons, so please do give me suggestions and feedback if needed :smile:

Source:
[com.vysp3r.RetroPlus.Source.svg](https://github.com/Vysp3r/RetroPlus/assets/80914457/4ab4eee3-7f43-4c38-b167-36b65b6745f6)

**Comment by Vysp3r** [comment]
I think it would be great if the icon didn't look rotated and the + didn't look like an x. It's not bad, but I don't think it's what  I want personally. You're free to propose something else tho. Thank you for taking the time to do that, I appreciate it.

**Comment by Vysp3r** [comment]
I preferred the first one to this one. I would advise using ChatGPT or something like that to get some idea's. I couldn't tell you what I want, because I don't mind the current icon, but if I am to change it, it needs to be something worth it.
