### ISSUE TITLE
Configure download directory per system

### ISSUE THREAD

**Issue by shadopz** [Vysp3r/RetroPlus#2]
This would be useful for setups using retroarch and the like. If you are downloading an xbox rom, it should map to a configured directory, etc

**Comment by Vysp3r** [comment]
Just to make sure I understand what you said properly, you want RetroPlus to automatically bind each systems to a directory?

**Comment by shadopsz** [comment]
> Just to make sure I understand what you said properly, you want RetroPlus to automatically bind each systems to a directory?

doesn’t need to be automatic per say, it can be configurable by the user. I can see many cases where even if the user isn’t necessarily suing something like retroarch, they may want to sort their ROMs into directories based on system. since this application doesn’t prompt the user for location each and every download (which would get annoying anyway), it would be nice to bind a particular system to a directory

**Comment by Vysp3r** [comment]
Yeah I mean at first I could definitely have people set them manually, but later down the road add a way to automate that process depending on the situation. Thanks for the input :)

**Comment by Vysp3r** [comment]
I'll add that in the next update.

**Comment by Vysp3r** [comment]
@shadopsz Does that look right to you or do you have a recommendation?
![image](https://github.com/Vysp3r/RetroPlus/assets/62019735/1cb16de1-4547-4965-b5d4-3a0e0c442cdc)

**Comment by shadopz** [comment]
that looks nice. are you able to show what it looks like to configure an additional system? .. i wish i was good with mock up software.

so with the implementation, you would keep changing that first 'choose a system' option and the directory underneath would change to show what is configured?

**Comment by Vysp3r** [comment]
@shadopz For your first question I don't really know what you want me to show you. You want a video of how to use that feature? 

As for your second question, you're absolutely right. I just thought it would be better to do it that way rather then having a really long list of text boxes.

**Comment by shadopz** [comment]
> @shadopz For your first question I don't really know what you want me to show you. You want a video of how to use that feature?
> 
> As for your second question, you're absolutely right. I just thought it would be better to do it that way rather then having a really long list of text boxes.

sounds like i might've figured it out lol so no need. i'm no UX expert but sounds good to me

**Comment by Vysp3r** [comment]
By default they will all be set to the download directory of the current user and if the directory you choose doesn't exists it will revert it back to the download directory of the current user.
