### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aluddin696** [Vysp3r/RetroPlus#20]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Fedora 36]
 - DE: [e.g. GNOME 42]
 - Type: [Source or Flathub]

**Additional context**

**Comment by Vysp3r** [comment]
You're missing some information ahah.

**Comment by Vysp3r** [comment]
I'll re-open it once you fill it properly.
