### ISSUE TITLE
Unable to search on Steam Deck - v0.1.4

### ISSUE THREAD

**Issue by tslpre** [Vysp3r/RetroPlus#24]
**Describe the bug**
I just updated to RetroPlus 0.1.4 On Steam Deck, and no matter if a global or system-specific search is made, the error "An unknown error occurred. Please report this on our Github."
Also, based on [this](https://github.com/Vysp3r/RetroPlus/issues/17#issuecomment-1939366354), I should see multiple sources and this is not the case (I checked in both the "Preferences" and the filters).

**To Reproduce**

1. Launch the application
2. Search for anything
3. The error "An unknown error occurred. Please report this on our Github." will be displayed.

**Expected behavior**
The search should report the results

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: SteamOS 3.5.7
- DE: KDE Plasma 5.27.5
- Type: Flathub

**Additional context**
Full log here: [https://pastes.io/kbbshty39t](https://pastes.io/kbbshty39t)

**Comment by Vysp3r** [comment]
I said I would add another source after the hotfix to fix the Vimm's Lair parser. I did not yet do another update including a parser.

Here's the message I sent on Telegram:
`I will rework the Vimm's Lair parser to be more effective at not getting broken for the next update. I will also include Myrient as a new source in case Vimm's parser breaks again so that we at least have an alternative while I fix the parser.`

**Comment by tslpre** [comment]
Apologies, as I noticed that the bug was closed and linked to the 0.1.4 milestone, I thought it was already done,my bad. Will wait for this bug to be closed.

thank you very much! :)

**Comment by Vysp3r** [comment]
Yeah I am sorry for the inconvenience. I know my application wasn't really reliable, but the parser worked for a month without any problem. I guess something got their attention and they started changing the code around to try to break the parsers. 

My friend will be helping me rework the parser in a few hours. I hope he will be able to explain to me a better solution then what I currently have that will be less prone to breaking.

**Comment by Vysp3r** [comment]
The search page parser rework is done. I only have the game page parser to finish. It should be done by the end of tonight. I'll start working on the Myrient parser after that. If all goes right, I should be pushing an update by the end of the weekend with those two things.

**Comment by Vysp3r** [comment]
Vimm's Lair parser rework is done!

I'll start working on the Myrient parser tomorrow after my gym session.

Let's hope this new parser last ahah.

**Comment by Vysp3r** [comment]
Everything is done. 
I'll now close the issue. 
Make sure to report any problem you encounter in the next version if you still have any :)
