### ISSUE TITLE
Completely non functional

### ISSUE THREAD

**Issue by Stez69** [Vysp3r/RetroPlus#26]
**Describe the bug**
I can't search anything and no roms ever load

**To Reproduce**
try to search anything or load anything

**Expected behavior**
A list of roms pertaining to the key word I typed in 
**Screenshots**
![image](https://github.com/Vysp3r/RetroPlus/assets/78983404/251ed9af-c7f4-4321-9f77-307bd826c291)

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - DE: Gnome 45
 - Type: Flathub
 - Memory: 16GB
**Additional context**

**Comment by Stez69** [comment]
I just saw that this bug has already been reported sorry ignore this

**Comment by Vysp3r** [comment]
@Stez69 It's currently fixed and will be available in the next update. You can check what's left for the next update to release here https://github.com/Vysp3r/RetroPlus/milestone/3.
