### ISSUE TITLE
unable to fetch a ROM list

### ISSUE THREAD

**Issue by Med21000** [Vysp3r/RetroPlus#29]
Flatpak version.

The app launch normally but trying to search for a ROM results in an error.

`flatpak run com.vysp3r.RetroPlus

(com.vysp3r.RetroPlus:2): Gtk-WARNING **: 19:30:43.593: GtkText - did not receive a focus-out event.
If you handle this event, you must return
GDK_EVENT_PROPAGATE so the default handler
gets the event as well

** (com.vysp3r.RetroPlus:2): WARNING **: 19:30:44.617: parser.vala:224: Unable to parse the id (tyle="width:auto"><a href= "48075">2 Games in 1: Dr. Mario + Puzzle League</a></td>)
`
 - OS: Ubuntu 23.10
 - DE: KDE
 - Type: Flathub

**Comment by Vysp3r** [comment]
Closing since duplice of https://github.com/Vysp3r/RetroPlus/issues/24.
