### ISSUE TITLE
RetroPlus 0.1.5 - unable to get results from Vimm's Lair

### ISSUE THREAD

**Issue by tslpre** [Vysp3r/RetroPlus#35]
**Describe the bug**
On Flatpak version v0.1.5, the search on Vimm's Lair does not produce any results. Error: "Nothing found, try searching again". Tried with "All" systems and individual ones, but the same error occurs.

**To Reproduce**
1. Go to search bar
2. Use "Vimm's Lair" as filter
3. Perform a search

**Expected behavior**
A filtered list of results should appear.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: SteamOS 3.5.7
 - DE: KDE Plasma 5.27.5
 - Type: Flathub

**Additional context**
Full log [here](https://pastes.io/plhfgwpujf).

**Comment by Vysp3r** [comment]
I'll start working on that and everything in v0.1.6 Thursday after my job.

**Comment by Vysp3r** [comment]
Closing since I am ending support support for RetroPlus.
Sorry for the inconvenience.
