### ISSUE TITLE
Unfiltered results search on Myrient. (RetroPlus 0.1.5)

### ISSUE THREAD

**Issue by tslpre** [Vysp3r/RetroPlus#36]
**Describe the bug**
On Flatpak version v0.1.5, the search on Myrient does not produce filtered results. Instead it seems that after any search you get a full list of games for the chosen system. Tried with different systems, but the same behaviour occurs.

**To Reproduce**
1. Go to search bar
2. Use "Myrient" as filter. It does not matter which system is chosen.
3. Perform a search to narrow down results using the given keywords
4. See a full, unfiltered list appears.

**Expected behavior**
If we search for specific keywords, the results should be filtered and only displaying the titles with contain the keywords.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: SteamOS 3.5.7
 - DE: KDE Plasma 5.27.5
 - Type: Flathub

**Additional context**
Full log [here](https://pastes.io/kc2jrjwarm).

**Comment by Vysp3r** [comment]
I may have actually forgotten to add the search parameter ahah. I'll add that to the next update. My bad.

**Comment by Vysp3r** [comment]
Closing since I am ending support support for RetroPlus.
Sorry for the inconvenience.
