### ISSUE TITLE
Add Internet Archive as a source

### ISSUE THREAD

**Issue by Snakeeater97** [Vysp3r/RetroPlus#6]
Vimm is slow for big files. It would be nice if we could add the roms megathread sources (myrient, internet archive).

**Comment by Vysp3r** [comment]
Myrient looks like it could be easily implemented. 

Internet archive on the other would be something else. Do you have a link with all the search parameters for internet archive to only display roms?

**Comment by Vysp3r** [comment]
@Snakeeater97 Just a friendly reminder that I am still waiting for the extra information I requested in my last comment before I can start working on it :)

**Comment by Snakeeater97** [comment]
> @Snakeeater97 Just a friendly reminder that I am still waiting for the extra information I requested in my last comment before I can start working on it :)

I don't know how to query all roms on the site. I think you would have to manually add each directory listed in the ROMs megathread. Maybe someone else knows...

**Comment by Vysp3r** [comment]
Closing since I am ending support support for RetroPlus.
Sorry for the inconvenience.
