### ISSUE TITLE
Can't install on steamdeck [BUG]

### ISSUE THREAD

**Issue by chanksworld** [Vysp3r/RetroPlus#9]
Using steam deck, trying to install from flathub, when i open the file it opens dolphin and I get an error" Could not open file:///home/deck/Desktop/com.vysp3r.RetroPlus.flatpakref"

not sure what to do?

**Comment by shadopsz** [comment]
are you sure you installed it? the error there looks like you placed a flatpakref file on your desktop

**Comment by chanksworld** [comment]
installed what?  where should i place the file? i downloaded the file on desktop but also downloaded source files and i get the same error there too when trying to run it

**Comment by Vysp3r** [comment]
@chanksworld Could you try running that in your terminal please: `flatpak install com.vysp3r.RetroPlus`

**Comment by shadopsz** [comment]
It looks like you pressed the 'Install' button [here](https://flathub.org/apps/com.vysp3r.RetroPlus)

Click the down arrow next to it for the manual steps.


Open the terminal and paste in the following:
```
flatpak install flathub com.vysp3r.RetroPlus
```
Go through the prompts (press 2 for user, then enter or type 'Y' and the permissions prompt) and after that you can search your apps by clicking the steam deck logo in the bottom left and start typing 'retroplus'.

Disclaimer: I am a stranger on the internet telling you to paste prompts into your terminal. Do additional research and trust no one.

**Comment by chanksworld** [comment]
thank you for the quick response stranger, that worked extremely well.. that probably should be added to the main page? thx again

**Comment by Vysp3r** [comment]
@chanksworld I don't think that's necessary since they show that command on the Flathub page. I will now be closing this issue since it has been resolved.
